baseURL = "https://ruby.digitalronin.com/"
languageCode = "en-us"
title = "DigitalRonin Ruby"
theme = "ananke"
publishDir = "docs"
googleAnalytics = "UA-36560094-5"

[params]
  show_reading_time = true
  twitter = "https://twitter.com/digitalronin"
  github = "https://github.com/digitalronin"
  featured_image = "/images/jeremy-thomas-75753-unsplash.jpg"
  recent_posts_number = 3
